[package]
name = "md"
version = "0.1.0"
edition = "2024"

[dependencies]
plotters = { version = "0.3.7", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "ttf"] }

clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["float_roundtrip"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
